@Card_Validate_Luhn__HostAddress = http://localhost:5148

### Validate a valid credit card number
POST {{Card_Validate_Luhn__HostAddress}}/api/credit-card/validate
Content-Type: application/json
Accept: application/json

{
  "cardNumber": "4532015112830366"
}

### Validate another valid credit card number with spaces
POST {{Card_Validate_Luhn__HostAddress}}/api/credit-card/validate
Content-Type: application/json
Accept: application/json

{
  "cardNumber": "4532 0151 1283 0366"
}

### Test with invalid credit card number
POST {{Card_Validate_Luhn__HostAddress}}/api/credit-card/validate
Content-Type: application/json
Accept: application/json

{
  "cardNumber": "1234567890123456"
}

### Test with empty credit card number
POST {{Card_Validate_Luhn__HostAddress}}/api/credit-card/validate
Content-Type: application/json
Accept: application/json

{
  "cardNumber": ""
}

### Test with non-digit characters
POST {{Card_Validate_Luhn__HostAddress}}/api/credit-card/validate
Content-Type: application/json
Accept: application/json

{
  "cardNumber": "4532abc1128d0366"
}

### Test with too short number
POST {{Card_Validate_Luhn__HostAddress}}/api/credit-card/validate
Content-Type: application/json
Accept: application/json

{
  "cardNumber": "12345"
}

### Test with too long number
POST {{Card_Validate_Luhn__HostAddress}}/api/credit-card/validate
Content-Type: application/json
Accept: application/json

{
  "cardNumber": "12345678901234567890"
}